solving
mate-academy/py-split-integer pull request #1080
Opened 2024-08-11 15:40 UTC by Poznanskyi

2024-08-12 05:05 UTC, Oleksl888 requested changes

2024-08-12 05:05 UTC, Oleksl888 commented on app/test_split_integer.py
> +        split_integer(17, 4) == [4, 4, 4, 5]
This data doesn't test that value is split in one part

2024-08-13 12:14 UTC, LiudmylaKulinchenko requested changes

2024-08-13 12:14 UTC, LiudmylaKulinchenko commented on app/test_split_integer.py
> +    ), "Should split into 4 parts"
Your test name isnt's similar to your message. You should've changed test logic after Oleksandrs comment, not message

2024-12-04 18:33 UTC, closed without merging