Solution
mate-academy/py-split-integer pull request #160
Opened 2022-10-04 18:15 UTC by serviza

2022-10-04 19:14 UTC, Menselface commented on app/test_split_integer.py
Code Style
Don't create unnecessary variables for simple tests:
Good example:

def test_():
    assert some_function_to_test() == [10]
    
 Don't forget to check [checklist ](https://github.com/mate-academy/py-split-integer/blob/master/checklist.md)before you pushing your solution
 assert sum(split_integer(17, 4) == 17

2022-10-04 19:17 UTC, Menselface commented on app/test_split_integer.py
Same here
assert split_integer(16, 4) == [4, 4, 4, 4]

2022-10-04 19:18 UTC, Menselface commented on app/test_split_integer.py
Same story

2022-10-04 19:19 UTC, Menselface commented on app/test_split_integer.py
+

2022-10-04 19:20 UTC, Menselface requested changes

2022-10-04 19:20 UTC, Menselface commented on app/test_split_integer.py
> +    assert parts[0] == parts[1] == 0
end here

2022-10-04 20:10 UTC, Menselface approved these changes
Super

2022-10-05 07:59 UTC, Y-Havryliv requested changes

2022-10-05 07:59 UTC, Y-Havryliv commented on app/test_split_integer.py
> +    assert parts == sorted(parts)
it's a bad test because `parts` is the result of `split_integer(32, 5)` and you're comparing `parts` to `parts`

2022-10-05 15:21 UTC, closed without merging