Split
mate-academy/py-split-integer pull request #203
Opened 2022-11-02 20:09 UTC by bythewaters

2022-11-03 08:55 UTC, IvanRamyk requested changes

2022-11-03 08:55 UTC, IvanRamyk commented on app/split_integer.py
> +split_integer(10, 6)
please, don't leave your test calls where you just writing tests

2022-11-03 08:55 UTC, IvanRamyk commented on app/test_split_integer.py
> +@pytest.mark.parametrize(
do not use `parametrize` when you want to test only one set of parameters

2022-11-03 08:55 UTC, IvanRamyk commented on app/test_split_integer.py
> +@pytest.mark.parametrize(
just write regular tests

2022-11-04 10:35 UTC, IvanRamyk requested changes

2022-11-04 10:35 UTC, IvanRamyk commented on app/test_split_integer.py
> +    assert sum(parts) == 32
```suggestion
    assert sum(parts) == split_integer(32, 6)
```
avoid using extra variables 

fix everywhere

2022-11-04 16:22 UTC, IvanRamyk requested changes

2022-11-04 16:22 UTC, IvanRamyk commented on app/test_split_integer.py
> +    assert split_integer(6, 1)[0] == 6
```suggestion
    assert split_integer(6, 1) == [6]
```
it's better to check the result explicitly

2022-11-04 16:22 UTC, IvanRamyk commented on app/test_split_integer.py
> +    assert split_integer(6, 1)[0] == 6
fix everywhere

2022-11-07 08:39 UTC, DmytroSvirsa approved these changes

2024-06-10 16:56 UTC, closed without merging